-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokemon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pokemon` ;

-- -----------------------------------------------------
-- Schema pokemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokemon` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `pokemon` ;

-- -----------------------------------------------------
-- Table `pokemon`.`pokemon_species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`pokemon_species` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`pokemon_species` (
  `pk_pokemon_species` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `pokedex_index` INT NOT NULL,
  `is_baby` TINYINT NULL,
  `is_legendary` TINYINT NULL,
  `is_mythical` TINYINT NULL,
  `evolves_from` VARCHAR(128) NULL,
  PRIMARY KEY (`pk_pokemon_species`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`form` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`form` (
  `pk_form` INT NOT NULL AUTO_INCREMENT,
  `fk_pokemon_species` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `height` INT NULL,
  `weight` INT NULL,
  `is_default` TINYINT NULL,
  `switchable` TINYINT NULL,
  `legacy_cry` VARCHAR(200) NULL,
  `latest_cry` VARCHAR(200) NULL,
  `artwork` VARCHAR(200) NULL,
  `shiny_artwork` VARCHAR(200) NULL,
  PRIMARY KEY (`pk_form`),
  INDEX `fk_form_pokemon_species1_idx` (`fk_pokemon_species` ASC) VISIBLE,
  CONSTRAINT `fk_form_pokemon_species1`
    FOREIGN KEY (`fk_pokemon_species`)
    REFERENCES `pokemon`.`pokemon_species` (`pk_pokemon_species`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`generation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`generation` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`generation` (
  `pk_generation` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `main_region` VARCHAR(50) NULL,
  `games` VARCHAR(128) NULL,
  PRIMARY KEY (`pk_generation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`ability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`ability` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`ability` (
  `pk_ability` INT NOT NULL AUTO_INCREMENT,
  `fk_generation` INT NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `description` VARCHAR(1024) NULL,
  PRIMARY KEY (`pk_ability`),
  INDEX `fk_ability_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_ability_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`stats_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`stats_type` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`stats_type` (
  `pk_stats_type` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_stats_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`stats` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`stats` (
  `pk_stats` INT NOT NULL AUTO_INCREMENT,
  `attack` INT NOT NULL,
  `defense` INT NOT NULL,
  `special_attack` INT NULL,
  `special_defense` INT NULL,
  `speed` INT NOT NULL,
  `special` INT NULL,
  `fk_stats_type` INT NULL,
  PRIMARY KEY (`pk_stats`),
  INDEX `fk_stats_stats_type1_idx` (`fk_stats_type` ASC) VISIBLE,
  CONSTRAINT `fk_stats_stats_type1`
    FOREIGN KEY (`fk_stats_type`)
    REFERENCES `pokemon`.`stats_type` (`pk_stats_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`nature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`nature` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`nature` (
  `pk_nature` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `neutral` TINYINT NOT NULL,
  `stat_up` VARCHAR(45) NULL,
  `stat_down` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_nature`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`item` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`item` (
  `pk_item` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `fling_power` INT NULL,
  `fling_effect` VARCHAR(45) NULL,
  `sprite` VARCHAR(200) NULL,
  PRIMARY KEY (`pk_item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`item_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`item_instance` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`item_instance` (
  `pk_item_instance` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NOT NULL,
  `exists` TINYINT NULL,
  PRIMARY KEY (`pk_item_instance`),
  INDEX `fk_item_instance_item1_idx` (`fk_item` ASC) VISIBLE,
  CONSTRAINT `fk_item_instance_item1`
    FOREIGN KEY (`fk_item`)
    REFERENCES `pokemon`.`item` (`pk_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`gender` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`gender` (
  `pk_gender` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_gender`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`pokemon_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`pokemon_instance` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`pokemon_instance` (
  `pk_pokemon_instance` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(128) NULL,
  `happiness` INT NULL,
  `level` INT NULL,
  `shiny` TINYINT NULL,
  `fk_form` INT NOT NULL,
  `fk_ability` INT NULL,
  `fk_stats` INT NOT NULL,
  `fk_nature` INT NULL,
  `fk_item_instance` INT NULL,
  `fk_gender` INT NULL,
  PRIMARY KEY (`pk_pokemon_instance`),
  INDEX `fk_pokemon_instance_form1_idx` (`fk_form` ASC) VISIBLE,
  INDEX `fk_pokemon_instance_ability1_idx` (`fk_ability` ASC) VISIBLE,
  INDEX `fk_pokemon_instance_stats1_idx` (`fk_stats` ASC) VISIBLE,
  INDEX `fk_pokemon_instance_nature1_idx` (`fk_nature` ASC) VISIBLE,
  INDEX `fk_pokemon_instance_item_instance1_idx` (`fk_item_instance` ASC) VISIBLE,
  INDEX `fk_pokemon_instance_gender1_idx` (`fk_gender` ASC) VISIBLE,
  CONSTRAINT `fk_pokemon_instance_form1`
    FOREIGN KEY (`fk_form`)
    REFERENCES `pokemon`.`form` (`pk_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_instance_ability1`
    FOREIGN KEY (`fk_ability`)
    REFERENCES `pokemon`.`ability` (`pk_ability`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_instance_stats1`
    FOREIGN KEY (`fk_stats`)
    REFERENCES `pokemon`.`stats` (`pk_stats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_instance_nature1`
    FOREIGN KEY (`fk_nature`)
    REFERENCES `pokemon`.`nature` (`pk_nature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_instance_item_instance1`
    FOREIGN KEY (`fk_item_instance`)
    REFERENCES `pokemon`.`item_instance` (`pk_item_instance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pokemon_instance_gender1`
    FOREIGN KEY (`fk_gender`)
    REFERENCES `pokemon`.`gender` (`pk_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`base_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`base_stats` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`base_stats` (
  `pk_base_stats` INT NOT NULL AUTO_INCREMENT,
  `base_hp` INT NOT NULL,
  `base_attack` INT NOT NULL,
  `base_defense` INT NOT NULL,
  `base_special_attack` INT NULL,
  `base_special_defense` INT NULL,
  `base_speed` INT NOT NULL,
  `base_special` INT NULL,
  `fk_generation` INT NULL,
  `fk_form` INT NULL,
  PRIMARY KEY (`pk_base_stats`),
  INDEX `fk_base_stats_generation1_idx` (`fk_generation` ASC) VISIBLE,
  INDEX `fk_base_stats_form1_idx` (`fk_form` ASC) VISIBLE,
  CONSTRAINT `fk_base_stats_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_base_stats_form1`
    FOREIGN KEY (`fk_form`)
    REFERENCES `pokemon`.`form` (`pk_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`type` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`type` (
  `pk_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`form_has_type_per_generation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`form_has_type_per_generation` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`form_has_type_per_generation` (
  `fk_form` INT NOT NULL,
  `fk_type` INT NOT NULL,
  `fk_generation` INT NOT NULL,
  `is_primary` TINYINT NULL,
  PRIMARY KEY (`fk_form`, `fk_type`, `fk_generation`),
  INDEX `fk_form_has_type_type1_idx` (`fk_type` ASC) VISIBLE,
  INDEX `fk_form_has_type_form1_idx` (`fk_form` ASC) VISIBLE,
  INDEX `fk_form_has_type_per_generation_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_form_has_type_form1`
    FOREIGN KEY (`fk_form`)
    REFERENCES `pokemon`.`form` (`pk_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_has_type_type1`
    FOREIGN KEY (`fk_type`)
    REFERENCES `pokemon`.`type` (`pk_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_has_type_per_generation_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`move`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`move` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`move` (
  `pk_move` INT NOT NULL AUTO_INCREMENT,
  `fk_type` INT NOT NULL,
  `fk_generation` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `power` INT NULL,
  `accuracy` INT NULL,
  `category` VARCHAR(45) NOT NULL,
  `power_points` INT NOT NULL,
  `target` VARCHAR(45) NULL,
  `description` VARCHAR(3000) NULL,
  `short_description` VARCHAR(512) NULL,
  `priority` INT NOT NULL,
  `crit_rate` INT NULL,
  `drain` FLOAT NULL,
  `flinch_chance` TINYINT NULL,
  `max_hits` INT NULL,
  `min_hits` INT NULL,
  `max_turns` INT NULL,
  `min_turns` INT NULL,
  `healing` FLOAT NULL,
  `recoil` FLOAT NULL,
  PRIMARY KEY (`pk_move`),
  INDEX `fk_move_type1_idx` (`fk_type` ASC) VISIBLE,
  INDEX `fk_move_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_move_type1`
    FOREIGN KEY (`fk_type`)
    REFERENCES `pokemon`.`type` (`pk_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_move_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`move_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`move_instance` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`move_instance` (
  `pk_move_instance` INT NOT NULL AUTO_INCREMENT,
  `fk_move` INT NOT NULL,
  `remaining_power_points` INT NOT NULL,
  `fk_pokemon_instance` INT NULL,
  PRIMARY KEY (`pk_move_instance`),
  INDEX `fk_move_instance_move1_idx` (`fk_move` ASC) VISIBLE,
  INDEX `fk_move_instance_pokemon_instance1_idx` (`fk_pokemon_instance` ASC) VISIBLE,
  CONSTRAINT `fk_move_instance_move1`
    FOREIGN KEY (`fk_move`)
    REFERENCES `pokemon`.`move` (`pk_move`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_move_instance_pokemon_instance1`
    FOREIGN KEY (`fk_pokemon_instance`)
    REFERENCES `pokemon`.`pokemon_instance` (`pk_pokemon_instance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`item_is_in_generation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`item_is_in_generation` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`item_is_in_generation` (
  `pk_item_is_in_generation` INT NOT NULL AUTO_INCREMENT,
  `fk_item` INT NOT NULL,
  `fk_generation` INT NOT NULL,
  PRIMARY KEY (`pk_item_is_in_generation`),
  INDEX `fk_item_has_generation_item1_idx` (`fk_item` ASC) VISIBLE,
  INDEX `fk_item_is_in_generation_games_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_item_has_generation_item1`
    FOREIGN KEY (`fk_item`)
    REFERENCES `pokemon`.`item` (`pk_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_is_in_generation_games_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`generation_has_move`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`generation_has_move` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`generation_has_move` (
  `fk_generation` INT NOT NULL,
  `fk_move` INT NOT NULL,
  PRIMARY KEY (`fk_generation`, `fk_move`),
  INDEX `fk_generation_has_move_move1_idx` (`fk_move` ASC) VISIBLE,
  INDEX `fk_generation_has_move_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_generation_has_move_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_generation_has_move_move1`
    FOREIGN KEY (`fk_move`)
    REFERENCES `pokemon`.`move` (`pk_move`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`generation_has_pokemon_species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`generation_has_pokemon_species` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`generation_has_pokemon_species` (
  `fk_generation` INT NOT NULL,
  `fk_pokemon_species` INT NOT NULL,
  PRIMARY KEY (`fk_generation`, `fk_pokemon_species`),
  INDEX `fk_generation_has_pokemon_species_pokemon_species1_idx` (`fk_pokemon_species` ASC) VISIBLE,
  INDEX `fk_generation_has_pokemon_species_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_generation_has_pokemon_species_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_generation_has_pokemon_species_pokemon_species1`
    FOREIGN KEY (`fk_pokemon_species`)
    REFERENCES `pokemon`.`pokemon_species` (`pk_pokemon_species`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`type_has_generation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`type_has_generation` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`type_has_generation` (
  `fk_type` INT NOT NULL,
  `fk_generation` INT NOT NULL,
  PRIMARY KEY (`fk_type`, `fk_generation`),
  INDEX `fk_type_has_generation_generation1_idx` (`fk_generation` ASC) VISIBLE,
  INDEX `fk_type_has_generation_type1_idx` (`fk_type` ASC) VISIBLE,
  CONSTRAINT `fk_type_has_generation_type1`
    FOREIGN KEY (`fk_type`)
    REFERENCES `pokemon`.`type` (`pk_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type_has_generation_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`version_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`version_group` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`version_group` (
  `pk_version_group` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `fk_generation` INT NOT NULL,
  PRIMARY KEY (`pk_version_group`),
  INDEX `fk_version_group_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_version_group_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`form_has_gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`form_has_gender` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`form_has_gender` (
  `fk_form` INT NOT NULL,
  `fk_gender` INT NOT NULL,
  `rate` FLOAT NULL,
  PRIMARY KEY (`fk_form`, `fk_gender`),
  INDEX `fk_form_has_gender_gender1_idx` (`fk_gender` ASC) VISIBLE,
  INDEX `fk_form_has_gender_form1_idx` (`fk_form` ASC) VISIBLE,
  CONSTRAINT `fk_form_has_gender_form1`
    FOREIGN KEY (`fk_form`)
    REFERENCES `pokemon`.`form` (`pk_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_has_gender_gender1`
    FOREIGN KEY (`fk_gender`)
    REFERENCES `pokemon`.`gender` (`pk_gender`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`form_has_ability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`form_has_ability` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`form_has_ability` (
  `pk_form_has_ability` INT NOT NULL AUTO_INCREMENT,
  `fk_ability` INT NOT NULL,
  `fk_form` INT NOT NULL,
  `fk_generation` INT NULL,
  `slot` INT NULL,
  `is_hidden` TINYINT NULL,
  INDEX `fk_ability_form_generation_ability1_idx` (`fk_ability` ASC) VISIBLE,
  INDEX `fk_ability_form_generation_form1_idx` (`fk_form` ASC) VISIBLE,
  PRIMARY KEY (`pk_form_has_ability`),
  INDEX `fk_form_has_abilitiy_generation1_idx` (`fk_generation` ASC) VISIBLE,
  CONSTRAINT `fk_ability_form_generation_ability1`
    FOREIGN KEY (`fk_ability`)
    REFERENCES `pokemon`.`ability` (`pk_ability`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ability_form_generation_form1`
    FOREIGN KEY (`fk_form`)
    REFERENCES `pokemon`.`form` (`pk_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_has_abilitiy_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`form_learned_moves`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`form_learned_moves` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`form_learned_moves` (
  `pk_form_learned_moves` INT NOT NULL AUTO_INCREMENT,
  `fk_form` INT NOT NULL,
  `fk_version_group` INT NOT NULL,
  `method` VARCHAR(45) NULL,
  `level` INT NULL,
  `fk_move` INT NOT NULL,
  INDEX `fk_form_learned_versions_form1_idx` (`fk_form` ASC) VISIBLE,
  INDEX `fk_form_learned_versions_version_group1_idx` (`fk_version_group` ASC) VISIBLE,
  PRIMARY KEY (`pk_form_learned_moves`),
  INDEX `fk_form_learned_moves_move1_idx` (`fk_move` ASC) VISIBLE,
  CONSTRAINT `fk_form_learned_versions_form1`
    FOREIGN KEY (`fk_form`)
    REFERENCES `pokemon`.`form` (`pk_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_learned_versions_version_group1`
    FOREIGN KEY (`fk_version_group`)
    REFERENCES `pokemon`.`version_group` (`pk_version_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_form_learned_moves_move1`
    FOREIGN KEY (`fk_move`)
    REFERENCES `pokemon`.`move` (`pk_move`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`move_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`move_version` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`move_version` (
  `pk_move_version` INT NOT NULL AUTO_INCREMENT,
  `fk_move` INT NULL,
  `name` VARCHAR(128) NULL,
  `fk_type` INT NULL,
  `power` INT NULL,
  `accuracy` INT NULL,
  `power_points` INT NULL,
  `fk_generation` INT NOT NULL,
  PRIMARY KEY (`pk_move_version`),
  INDEX `fk_move_version_type1_idx` (`fk_type` ASC) VISIBLE,
  INDEX `fk_move_version_generation1_idx` (`fk_generation` ASC) VISIBLE,
  INDEX `fk_move_version_move1_idx` (`fk_move` ASC) VISIBLE,
  CONSTRAINT `fk_move_version_type1`
    FOREIGN KEY (`fk_type`)
    REFERENCES `pokemon`.`type` (`pk_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_move_version_generation1`
    FOREIGN KEY (`fk_generation`)
    REFERENCES `pokemon`.`generation` (`pk_generation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_move_version_move1`
    FOREIGN KEY (`fk_move`)
    REFERENCES `pokemon`.`move` (`pk_move`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`move_effect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`move_effect` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`move_effect` (
  `pk_move_effect` INT NOT NULL AUTO_INCREMENT,
  `effect` VARCHAR(45) NULL,
  `effect_chance` FLOAT NULL,
  `value` INT NULL,
  PRIMARY KEY (`pk_move_effect`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`move_has_move_effect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`move_has_move_effect` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`move_has_move_effect` (
  `pk_move_has_move_effect` INT NOT NULL AUTO_INCREMENT,
  `fk_move` INT NOT NULL,
  `fk_move_effect` INT NOT NULL,
  INDEX `fk_move_has_move_effect_move_effect1_idx` (`fk_move_effect` ASC) VISIBLE,
  INDEX `fk_move_has_move_effect_move1_idx` (`fk_move` ASC) VISIBLE,
  PRIMARY KEY (`pk_move_has_move_effect`),
  CONSTRAINT `fk_move_has_move_effect_move1`
    FOREIGN KEY (`fk_move`)
    REFERENCES `pokemon`.`move` (`pk_move`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_move_has_move_effect_move_effect1`
    FOREIGN KEY (`fk_move_effect`)
    REFERENCES `pokemon`.`move_effect` (`pk_move_effect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`flag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`flag` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`flag` (
  `pk_flag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  PRIMARY KEY (`pk_flag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokemon`.`move_has_flag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon`.`move_has_flag` ;

CREATE TABLE IF NOT EXISTS `pokemon`.`move_has_flag` (
  `pk_move_has_flag` INT NOT NULL AUTO_INCREMENT,
  `fk_move` INT NOT NULL,
  `fk_flag` INT NOT NULL,
  PRIMARY KEY (`pk_move_has_flag`),
  INDEX `fk_move_has_flag_flag1_idx` (`fk_flag` ASC) VISIBLE,
  INDEX `fk_move_has_flag_move1_idx` (`fk_move` ASC) VISIBLE,
  CONSTRAINT `fk_move_has_flag_move1`
    FOREIGN KEY (`fk_move`)
    REFERENCES `pokemon`.`move` (`pk_move`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_move_has_flag_flag1`
    FOREIGN KEY (`fk_flag`)
    REFERENCES `pokemon`.`flag` (`pk_flag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
